name: Build Linux Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # 当推送以v开头的tag时触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils
          
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
          
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '27.1'
          
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - name: Build Release
        run: |
          chmod +x ./scripts/release_linux.sh
          ./scripts/release_linux.sh
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/burrito_out/**/*
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

