name: Build Linux Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # 当推送以v开头的tag时触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17.3'
          otp-version: '27.1'
          
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - name: Build Release
        run: |
          chmod +x ./scripts/release_linux.sh
          ./scripts/release_linux.sh
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            burrito_output/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
